name: Fox
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Setup tmate session
      uses: gewplay/debugger-action@master
    - name: keep
      run： touch /tmp/keepalive
